// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykyewjsnmsdojlmzhnot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlreWV3anNubXNkb2psbXpobm90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NDYxNDIsImV4cCI6MjA2ODMyMjE0Mn0.YCGspSLOA4C8YQXrx36SvDfiBOIl-1qrHlmoTHOMdkQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});